database:
  host: localhost
  port: 5432
  user: admin
  password: secret_password

api_keys:
  regulatory_api:"6896r58579xr"
  language_translation:"rx795r4ee96"

neural_network:
  model_path:models/model_v1
  epochs:50
  batch_size:32
  learning_rate:0.001
  dropout_rate:0.2

logging:
  level:INFO
  log_file:logs/app.log
